server:
  port: 8080
dubbo:
  application:
         name: boot-consumer
         timeout: 300001
  registry: {address: 'zookeeper://127.0.0.1:2181', check: false}
  monitor: {protocol: registry}
  consumer: {timeout: 30000}
spring:
  application: {name: openfeign-server}
msg:
  user:
    id: 7772
    age: 10
    arr: [1, 2, 3, 4, 5, 6]
    arrlist: [1, 2, 3, 4, 5]
    list:
    - {id: 2, age: 三十}
    - {id: 3, age: 四十}
    - {id: 4, age: 五十}
    - {id: 5, age: 六十}
    haMap: {value1: value1, value2: value2, value3: value3}
    arrHash:
    - {value1: 张三}
    - {value2: 李斯}
    arrHashUser:
    - value1: {id: 22, age: 赵钱}
    - value2: {id: 33, age: 孙李}
